# Generated by Django 5.0.7 on 2024-11-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_jobapplication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='user',
        ),
    ]
